import { useState, useEffect, useCallback } from 'react';
import type { BrainEntry, BrainDetail, BrainValidationResult, SignalEntry } from '../types';
import {
  ListBrains as ListBrainsBinding,
  GetBrain as GetBrainBinding,
  MatchBrains as MatchBrainsBinding,
  ValidateBrain as ValidateBrainBinding,
  ListSignals as ListSignalsBinding,
  GetSignalsByDomain as GetSignalsByDomainBinding,
  GetBrainDirs as GetBrainDirsBinding,
  SetBrainProjectPath as SetBrainProjectPathBinding,
  AutoDistillBrains as AutoDistillBrainsBinding,
} from '../../wailsjs/go/main/App';
import { EventsOn, EventsOff } from '../../wailsjs/runtime/runtime';

export interface AutoDistillResult {
  domain: string;
  brainId: string;
  path: string;
  signals: number;
  usedLlm: boolean;
}

export function useBrain() {
  const [brains, setBrains] = useState<BrainEntry[]>([]);
  const [selectedBrain, setSelectedBrain] = useState<BrainDetail | null>(null);
  const [matchedBrains, setMatchedBrains] = useState<BrainEntry[]>([]);
  const [signals, setSignals] = useState<SignalEntry[]>([]);
  const [brainDirs, setBrainDirs] = useState<string[]>([]);
  const [validation, setValidation] = useState<BrainValidationResult | null>(null);
  const [autoGenerated, setAutoGenerated] = useState<AutoDistillResult[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  // Subscribe to brain events
  useEffect(() => {
    const matchHandler = (data: { matches: BrainEntry[]; count: number }) => {
      setMatchedBrains(data.matches || []);
    };

    const autoGenHandler = (data: { results: AutoDistillResult[]; count: number }) => {
      setAutoGenerated(data.results || []);
    };

    EventsOn('brain:matched', matchHandler);
    EventsOn('brain:auto-generated', autoGenHandler);

    return () => {
      EventsOff('brain:matched');
      EventsOff('brain:auto-generated');
    };
  }, []);

  // Load all brains
  const loadBrains = useCallback(async () => {
    try {
      setIsLoading(true);
      const result = await ListBrainsBinding();
      setBrains(result || []);
    } catch (err) {
      console.error('Failed to load brains:', err);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Load a specific brain
  const loadBrain = useCallback(async (id: string) => {
    try {
      setIsLoading(true);
      const result = await GetBrainBinding(id);
      setSelectedBrain(result);
      return result;
    } catch (err) {
      console.error('Failed to load brain:', err);
      return null;
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Match brains against context
  const matchBrains = useCallback(async (keywords: string[], filePaths: string[], entities: string[]) => {
    try {
      const result = await MatchBrainsBinding(keywords, filePaths, entities);
      setMatchedBrains(result || []);
      return result || [];
    } catch (err) {
      console.error('Failed to match brains:', err);
      return [];
    }
  }, []);

  // Validate a brain
  const validateBrain = useCallback(async (id: string) => {
    try {
      const result = await ValidateBrainBinding(id);
      setValidation(result);
      return result;
    } catch (err) {
      console.error('Failed to validate brain:', err);
      return null;
    }
  }, []);

  // Load signals
  const loadSignals = useCallback(async () => {
    try {
      const result = await ListSignalsBinding();
      setSignals(result || []);
    } catch (err) {
      console.error('Failed to load signals:', err);
    }
  }, []);

  // Load signals for a domain
  const loadSignalsByDomain = useCallback(async (domain: string) => {
    try {
      const result = await GetSignalsByDomainBinding(domain);
      return result || [];
    } catch (err) {
      console.error('Failed to load signals by domain:', err);
      return [];
    }
  }, []);

  // Load brain directories
  const loadBrainDirs = useCallback(async () => {
    try {
      const result = await GetBrainDirsBinding();
      setBrainDirs(result || []);
    } catch (err) {
      console.error('Failed to load brain dirs:', err);
    }
  }, []);

  // Set project path for brain resolution
  const setProjectPath = useCallback(async (path: string) => {
    try {
      await SetBrainProjectPathBinding(path);
    } catch (err) {
      console.error('Failed to set brain project path:', err);
    }
  }, []);

  // Trigger auto-distillation of signals into brains
  const autoDistill = useCallback(async () => {
    try {
      setIsLoading(true);
      const result = await AutoDistillBrainsBinding();
      if (result && result.length > 0) {
        setAutoGenerated(result);
        // Reload brains to include new ones
        await loadBrains();
      }
      return result || [];
    } catch (err) {
      console.error('Failed to auto-distill brains:', err);
      return [];
    } finally {
      setIsLoading(false);
    }
  }, [loadBrains]);

  // Dismiss auto-generated notification
  const dismissAutoGenerated = useCallback(() => {
    setAutoGenerated([]);
  }, []);

  return {
    brains,
    selectedBrain,
    matchedBrains,
    signals,
    brainDirs,
    validation,
    autoGenerated,
    isLoading,
    loadBrains,
    loadBrain,
    matchBrains,
    validateBrain,
    loadSignals,
    loadSignalsByDomain,
    loadBrainDirs,
    setProjectPath,
    setSelectedBrain,
    autoDistill,
    dismissAutoGenerated,
  };
}
