import { useState, useEffect } from 'react';
import {
  Brain,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle,
  FileText,
  Tag,
  Search,
  Zap,
  FolderOpen,
  RefreshCw,
  Sparkles,
  X,
} from 'lucide-react';
import { useBrain } from '../../hooks/useBrain';
import type { BrainEntry, BrainDetail, SignalEntry } from '../../types';

type BrainTab = 'index' | 'signals';

export function BrainView() {
  const {
    brains,
    selectedBrain,
    signals,
    brainDirs,
    validation,
    autoGenerated,
    isLoading,
    loadBrains,
    loadBrain,
    validateBrain,
    loadSignals,
    loadBrainDirs,
    setSelectedBrain,
    autoDistill,
    dismissAutoGenerated,
  } = useBrain();

  const [activeTab, setActiveTab] = useState<BrainTab>('index');
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    loadBrains();
    loadBrainDirs();
  }, [loadBrains, loadBrainDirs]);

  const filteredBrains = brains.filter((b) => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      b.name.toLowerCase().includes(q) ||
      b.description.toLowerCase().includes(q) ||
      b.keywords.some((k) => k.toLowerCase().includes(q)) ||
      b.entities.some((e) => e.toLowerCase().includes(q))
    );
  });

  const handleSelectBrain = async (brain: BrainEntry) => {
    if (selectedBrain?.id === brain.id) {
      setSelectedBrain(null);
      return;
    }
    await loadBrain(brain.id);
  };

  const handleValidate = async (id: string) => {
    await validateBrain(id);
  };

  const handleLoadSignals = async () => {
    await loadSignals();
    setActiveTab('signals');
  };

  return (
    <div className="flex flex-col h-full bg-slate-900">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700">
        <div className="flex items-center gap-2">
          <Brain className="w-5 h-5 text-purple-400" />
          <h2 className="text-sm font-semibold text-slate-200">Domain Knowledge</h2>
          <span className="px-1.5 py-0.5 text-xs bg-slate-700 rounded-full text-slate-400">
            {brains.length}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={autoDistill}
            className="p-1.5 text-slate-400 hover:text-purple-300 transition-colors"
            title="Auto-distill signals into brains"
          >
            <Sparkles className="w-4 h-4" />
          </button>
          <button
            onClick={() => { loadBrains(); loadBrainDirs(); }}
            className="p-1.5 text-slate-400 hover:text-slate-200 transition-colors"
            title="Refresh"
          >
            <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Auto-generated notification */}
      {autoGenerated.length > 0 && (
        <div className="flex items-center gap-2 px-4 py-2 bg-purple-900/30 border-b border-purple-800/50 text-xs">
          <Sparkles className="w-3.5 h-3.5 text-purple-400 flex-shrink-0" />
          <span className="text-purple-200 flex-1">
            {autoGenerated.length} brain{autoGenerated.length > 1 ? 's' : ''} auto-generated from signals:{' '}
            {autoGenerated.map((r) => r.domain).join(', ')}
          </span>
          <button
            onClick={dismissAutoGenerated}
            className="p-0.5 text-purple-400 hover:text-purple-200 transition-colors"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* Tabs */}
      <div className="flex border-b border-slate-700">
        <button
          onClick={() => setActiveTab('index')}
          className={`flex items-center gap-1.5 px-4 py-2 text-xs transition-colors border-b-2 ${
            activeTab === 'index'
              ? 'border-purple-500 text-slate-100'
              : 'border-transparent text-slate-400 hover:text-slate-200'
          }`}
        >
          <Brain className="w-3.5 h-3.5" />
          Brains
        </button>
        <button
          onClick={handleLoadSignals}
          className={`flex items-center gap-1.5 px-4 py-2 text-xs transition-colors border-b-2 ${
            activeTab === 'signals'
              ? 'border-amber-500 text-slate-100'
              : 'border-transparent text-slate-400 hover:text-slate-200'
          }`}
        >
          <Zap className="w-3.5 h-3.5" />
          Signals
          {signals.length > 0 && (
            <span className="px-1 py-0.5 text-xs bg-amber-900/50 text-amber-400 rounded">
              {signals.length}
            </span>
          )}
        </button>
      </div>

      {/* Search (brains tab only) */}
      {activeTab === 'index' && (
        <div className="px-3 py-2 border-b border-slate-800">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search brains..."
              className="w-full pl-8 pr-3 py-1.5 text-xs bg-slate-800 border border-slate-700 rounded text-slate-200 placeholder-slate-500 focus:outline-none focus:border-purple-500"
            />
          </div>
        </div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-y-auto">
        {activeTab === 'index' && (
          <BrainIndex
            brains={filteredBrains}
            selectedBrain={selectedBrain}
            validation={validation}
            onSelect={handleSelectBrain}
            onValidate={handleValidate}
          />
        )}
        {activeTab === 'signals' && <SignalList signals={signals} />}
      </div>

      {/* Brain directories footer */}
      {brainDirs.length > 0 && (
        <div className="px-3 py-2 border-t border-slate-800 text-xs text-slate-500">
          <div className="flex items-center gap-1">
            <FolderOpen className="w-3 h-3" />
            <span>Scanning: {brainDirs.map((d) => d.split('/').slice(-2).join('/')).join(', ')}</span>
          </div>
        </div>
      )}
    </div>
  );
}

// =============================================================================
// Brain Index
// =============================================================================

interface BrainIndexProps {
  brains: BrainEntry[];
  selectedBrain: BrainDetail | null;
  validation: import('../../types').BrainValidationResult | null;
  onSelect: (brain: BrainEntry) => void;
  onValidate: (id: string) => void;
}

function BrainIndex({ brains, selectedBrain, validation, onSelect, onValidate }: BrainIndexProps) {
  if (brains.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-500 p-8">
        <Brain className="w-12 h-12 mb-3 opacity-30" />
        <p className="text-sm font-medium mb-1">No brains found</p>
        <p className="text-xs text-center">
          Create brain YAML files in <code className="text-purple-400">.boatman/brains/</code> to provide
          domain knowledge to agents.
        </p>
      </div>
    );
  }

  return (
    <div className="divide-y divide-slate-800">
      {brains.map((brain) => {
        const isSelected = selectedBrain?.id === brain.id;
        return (
          <div key={brain.id}>
            {/* Brain header */}
            <button
              onClick={() => onSelect(brain)}
              className="w-full flex items-start gap-3 px-4 py-3 hover:bg-slate-800/50 transition-colors text-left"
            >
              <div className="mt-0.5">
                {isSelected ? (
                  <ChevronDown className="w-4 h-4 text-purple-400" />
                ) : (
                  <ChevronRight className="w-4 h-4 text-slate-500" />
                )}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-slate-200">{brain.name}</span>
                  <ConfidenceBadge confidence={brain.confidence} />
                </div>
                <p className="text-xs text-slate-400 mt-0.5 line-clamp-2">{brain.description}</p>
                <div className="flex flex-wrap gap-1 mt-1.5">
                  {brain.keywords.slice(0, 5).map((kw) => (
                    <span
                      key={kw}
                      className="px-1.5 py-0.5 text-xs bg-purple-900/30 text-purple-300 rounded"
                    >
                      {kw}
                    </span>
                  ))}
                  {brain.entities.slice(0, 3).map((ent) => (
                    <span
                      key={ent}
                      className="px-1.5 py-0.5 text-xs bg-blue-900/30 text-blue-300 rounded"
                    >
                      {ent}
                    </span>
                  ))}
                  {brain.keywords.length + brain.entities.length > 8 && (
                    <span className="text-xs text-slate-500">
                      +{brain.keywords.length + brain.entities.length - 8} more
                    </span>
                  )}
                </div>
              </div>
            </button>

            {/* Expanded detail */}
            {isSelected && selectedBrain && (
              <BrainDetailView
                brain={selectedBrain}
                validation={validation}
                onValidate={() => onValidate(brain.id)}
              />
            )}
          </div>
        );
      })}
    </div>
  );
}

// =============================================================================
// Brain Detail View
// =============================================================================

interface BrainDetailViewProps {
  brain: BrainDetail;
  validation: import('../../types').BrainValidationResult | null;
  onValidate: () => void;
}

function BrainDetailView({ brain, validation, onValidate }: BrainDetailViewProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(brain.sections.map((s) => s.title))
  );

  const toggleSection = (title: string) => {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      if (next.has(title)) next.delete(title);
      else next.add(title);
      return next;
    });
  };

  return (
    <div className="bg-slate-850 border-t border-slate-800">
      {/* Meta row */}
      <div className="flex items-center gap-4 px-4 py-2 bg-slate-800/50 text-xs text-slate-400">
        <span>v{brain.version}</span>
        {brain.lastUpdated && <span>Updated: {brain.lastUpdated}</span>}
        {brain.filePatterns.length > 0 && (
          <span className="flex items-center gap-1">
            <FolderOpen className="w-3 h-3" />
            {brain.filePatterns.join(', ')}
          </span>
        )}
        <button
          onClick={onValidate}
          className="ml-auto text-xs text-purple-400 hover:text-purple-300 transition-colors"
        >
          Validate
        </button>
      </div>

      {/* Validation result */}
      {validation && (
        <div className={`px-4 py-2 text-xs border-t border-slate-800 ${
          validation.valid ? 'bg-green-900/20' : 'bg-red-900/20'
        }`}>
          <div className="flex items-center gap-1.5">
            {validation.valid ? (
              <><CheckCircle className="w-3.5 h-3.5 text-green-400" /> <span className="text-green-400">Valid</span></>
            ) : (
              <><AlertTriangle className="w-3.5 h-3.5 text-red-400" /> <span className="text-red-400">{validation.errors.length} error(s)</span></>
            )}
          </div>
          {validation.errors.map((err, i) => (
            <div key={i} className="text-red-300 mt-1 pl-5">- {err}</div>
          ))}
          {validation.stale.length > 0 && (
            <div className="mt-1.5">
              <span className="text-amber-400">Stale references:</span>
              {validation.stale.map((s, i) => (
                <div key={i} className="text-amber-300 pl-5">- {s.path} ({s.reason})</div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Sections */}
      <div className="divide-y divide-slate-800">
        {brain.sections.map((section) => {
          const isExpanded = expandedSections.has(section.title);
          return (
            <div key={section.title}>
              <button
                onClick={() => toggleSection(section.title)}
                className="w-full flex items-center gap-2 px-4 py-2 hover:bg-slate-800/30 transition-colors text-left"
              >
                {isExpanded ? (
                  <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                ) : (
                  <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
                )}
                <FileText className="w-3.5 h-3.5 text-purple-400" />
                <span className="text-xs font-medium text-slate-300">{section.title}</span>
              </button>
              {isExpanded && (
                <div className="px-10 pb-3 text-xs text-slate-300 whitespace-pre-wrap leading-relaxed">
                  {section.content}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* References */}
      {brain.references.length > 0 && (
        <div className="border-t border-slate-800 px-4 py-2">
          <div className="flex items-center gap-1.5 mb-1.5">
            <Tag className="w-3 h-3 text-slate-400" />
            <span className="text-xs font-medium text-slate-400">References</span>
          </div>
          <div className="space-y-1">
            {brain.references.map((ref) => (
              <div key={ref.path} className="flex items-center gap-2 text-xs">
                <code className="text-cyan-400 font-mono">{ref.path}</code>
                <span className="text-slate-500">- {ref.description}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// =============================================================================
// Signal List
// =============================================================================

interface SignalListProps {
  signals: SignalEntry[];
}

function SignalList({ signals }: SignalListProps) {
  if (signals.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-500 p-8">
        <Zap className="w-12 h-12 mb-3 opacity-30" />
        <p className="text-sm font-medium mb-1">No signals detected</p>
        <p className="text-xs text-center">
          Signals are collected automatically during agent workflows
          when knowledge gaps are detected.
        </p>
      </div>
    );
  }

  // Group by domain
  const grouped = signals.reduce<Record<string, SignalEntry[]>>((acc, sig) => {
    if (!acc[sig.domain]) acc[sig.domain] = [];
    acc[sig.domain].push(sig);
    return acc;
  }, {});

  return (
    <div className="divide-y divide-slate-800">
      {Object.entries(grouped).map(([domain, domainSignals]) => (
        <div key={domain} className="px-4 py-3">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-sm font-medium text-slate-200 capitalize">{domain}</span>
            <span className="px-1.5 py-0.5 text-xs bg-amber-900/50 text-amber-400 rounded">
              {domainSignals.length}
            </span>
          </div>
          <div className="space-y-2">
            {domainSignals.map((sig, i) => (
              <div key={i} className="flex items-start gap-2 text-xs">
                <SignalTypeBadge type={sig.type} />
                <div className="flex-1 min-w-0">
                  <p className="text-slate-300 truncate">{sig.details || 'No details'}</p>
                  <div className="flex items-center gap-3 mt-0.5 text-slate-500">
                    <span>x{sig.count}</span>
                    <span>Last: {new Date(sig.lastSeen).toLocaleDateString()}</span>
                    {sig.filePaths.length > 0 && (
                      <span className="truncate">{sig.filePaths[0]}</span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// =============================================================================
// Utility Components
// =============================================================================

function ConfidenceBadge({ confidence }: { confidence: number }) {
  const pct = Math.round(confidence * 100);
  const color =
    pct >= 80 ? 'bg-green-900/30 text-green-400' :
    pct >= 50 ? 'bg-amber-900/30 text-amber-400' :
    'bg-red-900/30 text-red-400';

  return (
    <span className={`px-1.5 py-0.5 text-xs rounded ${color}`}>
      {pct}%
    </span>
  );
}

function SignalTypeBadge({ type }: { type: string }) {
  const config: Record<string, { label: string; color: string }> = {
    review_failure: { label: 'Review', color: 'bg-red-900/30 text-red-400' },
    refactor_loop: { label: 'Refactor', color: 'bg-orange-900/30 text-orange-400' },
    repeated_file_read: { label: 'File Read', color: 'bg-blue-900/30 text-blue-400' },
    user_correction: { label: 'Correction', color: 'bg-purple-900/30 text-purple-400' },
    error_retry_loop: { label: 'Retry', color: 'bg-amber-900/30 text-amber-400' },
  };

  const cfg = config[type] || { label: type, color: 'bg-slate-700 text-slate-400' };

  return (
    <span className={`px-1.5 py-0.5 text-xs rounded flex-shrink-0 ${cfg.color}`}>
      {cfg.label}
    </span>
  );
}
